[build]
  command = "npm run build"
  publish = ".next"

[[functions]]
  directory = ".netlify/functions-internal"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"